theme: just-the-docs
title: NMSK Modelling Guidelines
description: A general overview and guidelines for the data processing and NMSK modelling pipeline commonly used within PRECISE

url: https://matthew-hambly.github.io/nmsk-modelling-guidelines-testing

color_scheme: custom_theme

back_to_top: true
back_to_top_text: "Back to top"
heading_anchors: false

footer_content: "Warning: this is still a work in progress."
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
